# Use root/password as user/password credentials
services:
  COMS363-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv=""
    restart: always
    ports:
      - ${projport}:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ${basepath}/${projname}
  adminer:
    image: adminer
    restart: always
volumes:
  coms363db:
    
